services:
  git-stats:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: git-stats-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
      - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.example-app.rule=Host(`stats.elmountahi.dev`)"
      - "traefik.http.services.example-app.loadbalancer.server.port=3000"
      - "traefik.http.routers.example-app.tls=true"
      - "traefik.http.routers.example-app.tls.certresolver=myresolver"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true
